In [3]:
import numpy as np

In [159]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [160]:
a[a < 0]

array([-2, -1, -6, -7])

In [161]:
# How many negative numbers are there?

len(a[a < 0])

4

In [162]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [163]:
# How many positive numbers are there?

len(a[a > 0])

5

In [164]:
a[(a > 0) & (a % 2 == 0)]

array([ 4, 10, 12])

In [165]:
# How many even positive numbers are there?
len(a[(a > 0) & (a % 2 == 0)])

3

In [166]:
a + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [167]:
(a + 3)  [a > 0]

array([ 7, 13, 15, 26,  6])

In [168]:
# If you were to add 3 to each data point, how many positive numbers would there be?
len((a +3)[a > 0])

5

In [169]:
a ** 2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [170]:
# If you squared each number, what would the new mean and standard deviation be?
(a ** 2).mean(), (a ** 2).std()

(74.0, 144.0243035046516)

In [171]:
a.mean()

3.0

In [172]:
# A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.
a - (a).mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [44]:
# Calculate the z-score for each data point.
(a-a.mean())/a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

# Life w/o numpy to life with numpy

## Setup 1

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Use python's built in functionality/operators to determine the following:

In [173]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [174]:
sum_of_a = sum(a)
sum_of_a

55

In [175]:
min_of_a = min(a)
min_of_a

1

In [176]:
max_of_a = max(a)
max_of_a

10

In [177]:
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

In [178]:
product_of_a = 1
for item in a:
    product_of_a *= item
    
product_of_a   

3628800

In [179]:
squares_of_a = [number **2 for number in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [180]:
odds_in_a = [number for number in a if number%2 ==1]
odds_in_a

[1, 3, 5, 7, 9]

In [181]:
evens_in_a = [number for number in a if number%2 ==0]
evens_in_a

[2, 4, 6, 8, 10]

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

b = [

    [3, 4, 5],
    [6, 7, 8]
       
]

In [187]:
b = np.array([
                [3, 4, 5],
                [6, 7, 8]
            ])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [188]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [189]:
min_of_b = b.min()
min_of_b

3

In [190]:
max_of_b = b.max()
max_of_b

8

In [191]:
mean_of_b = b.mean()
mean_of_b

5.5

In [192]:
b.prod()

20160

In [193]:
squares_of_b = b**2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [194]:
odds_in_b= b[b%2 == 1]
odds_in_b

array([3, 5, 7])

In [195]:
evens_in_b= b[b%2 == 0]
evens_in_b

array([4, 6, 8])

In [196]:
b.shape

(2, 3)

In [197]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [198]:
b.reshape(1,6,-1)

array([[[3],
        [4],
        [5],
        [6],
        [7],
        [8]]])

In [199]:
b.reshape(-1)

array([3, 4, 5, 6, 7, 8])

# Setup 3

c = [

    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    
]

In [200]:
c = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

In [201]:
c.std()

2.581988897471611

In [202]:
c.var()

6.666666666666667

In [203]:
c.shape

(3, 3)

In [204]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [205]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [125]:
 (c*c.transpose())

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [126]:
 (c*c.transpose()).sum()

261

In [127]:
 (c*c.transpose()).prod()

131681894400

# Setup 4

d = [

    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
    
]

In [129]:
d = np.array(
    [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
    ])

d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [206]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [207]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [208]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [209]:
d[d < 0]

array([-90, -30, -45, -45])

In [210]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [211]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [212]:
len(np.unique(d))

11

In [213]:
d.shape

(3, 6)

In [214]:
d.transpose()

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [215]:
(d.transpose()).shape

(6, 3)

In [142]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])